syntax = "proto3";
package foskv.raft;

message RequestHeader {
  uint64 cluster_id = 1;
  uint64 member_id = 2;
  uint64 term = 3;
}

message RequestVoteRequest {
  RequestHeader header = 1;
  uint64 last_log_index = 2;
  uint64 last_log_term = 3;
}

message RequestVoteResponse {
  uint64 term = 1;
  bool vote_granted = 2;
}

message LogEntry {
  uint64 log_term = 1;
  uint64 log_index = 2;
  bytes command = 3;
}

message AppendEntriesRequest {
  RequestHeader header = 1;
  uint64 prev_log_index = 2;
  uint64 prev_log_term = 3;
  repeated LogEntry entries = 4;
  uint64 leader_commit = 5;
}

message AppendEntriesResponse {
  uint64 term = 1;
  bool success = 2;
}

message InstallSnapshotRequest {
  RequestHeader header = 1;
  uint64 last_include_index = 2;
  uint64 last_include_term = 3;
  uint64 offset = 4;
  bytes data = 5;
  bool done = 6;
}

message InstallSnapshotResponse {
  uint64 term = 1;
}