// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foskv/api/foskvserverpb/raft_internal.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_foskv_2fapi_2ffoskvserverpb_2fraft_5finternal_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_foskv_2fapi_2ffoskvserverpb_2fraft_5finternal_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "foskv/api/foskvserverpb/rpc.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_foskv_2fapi_2ffoskvserverpb_2fraft_5finternal_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_foskv_2fapi_2ffoskvserverpb_2fraft_5finternal_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_foskv_2fapi_2ffoskvserverpb_2fraft_5finternal_2eproto;
namespace foskvserverpb {
class InternalRaftRequest;
struct InternalRaftRequestDefaultTypeInternal;
extern InternalRaftRequestDefaultTypeInternal _InternalRaftRequest_default_instance_;
class RequestHeader;
struct RequestHeaderDefaultTypeInternal;
extern RequestHeaderDefaultTypeInternal _RequestHeader_default_instance_;
}  // namespace foskvserverpb
PROTOBUF_NAMESPACE_OPEN
template<> ::foskvserverpb::InternalRaftRequest* Arena::CreateMaybeMessage<::foskvserverpb::InternalRaftRequest>(Arena*);
template<> ::foskvserverpb::RequestHeader* Arena::CreateMaybeMessage<::foskvserverpb::RequestHeader>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace foskvserverpb {

// ===================================================================

class RequestHeader final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:foskvserverpb.RequestHeader) */ {
 public:
  inline RequestHeader() : RequestHeader(nullptr) {}
  ~RequestHeader() override;
  explicit PROTOBUF_CONSTEXPR RequestHeader(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RequestHeader(const RequestHeader& from);
  RequestHeader(RequestHeader&& from) noexcept
    : RequestHeader() {
    *this = ::std::move(from);
  }

  inline RequestHeader& operator=(const RequestHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestHeader& operator=(RequestHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const RequestHeader* internal_default_instance() {
    return reinterpret_cast<const RequestHeader*>(
               &_RequestHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RequestHeader& a, RequestHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(RequestHeader* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RequestHeader>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RequestHeader& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RequestHeader& from) {
    RequestHeader::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestHeader* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "foskvserverpb.RequestHeader";
  }
  protected:
  explicit RequestHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIDFieldNumber = 1,
  };
  // uint64 ID = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:foskvserverpb.RequestHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_foskv_2fapi_2ffoskvserverpb_2fraft_5finternal_2eproto;
};
// -------------------------------------------------------------------

class InternalRaftRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:foskvserverpb.InternalRaftRequest) */ {
 public:
  inline InternalRaftRequest() : InternalRaftRequest(nullptr) {}
  ~InternalRaftRequest() override;
  explicit PROTOBUF_CONSTEXPR InternalRaftRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InternalRaftRequest(const InternalRaftRequest& from);
  InternalRaftRequest(InternalRaftRequest&& from) noexcept
    : InternalRaftRequest() {
    *this = ::std::move(from);
  }

  inline InternalRaftRequest& operator=(const InternalRaftRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline InternalRaftRequest& operator=(InternalRaftRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InternalRaftRequest& default_instance() {
    return *internal_default_instance();
  }
  enum TypeCase {
    kPut = 1,
    kGet = 2,
    kDelete = 3,
    TYPE_NOT_SET = 0,
  };

  static inline const InternalRaftRequest* internal_default_instance() {
    return reinterpret_cast<const InternalRaftRequest*>(
               &_InternalRaftRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(InternalRaftRequest& a, InternalRaftRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(InternalRaftRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InternalRaftRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InternalRaftRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InternalRaftRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InternalRaftRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InternalRaftRequest& from) {
    InternalRaftRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InternalRaftRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "foskvserverpb.InternalRaftRequest";
  }
  protected:
  explicit InternalRaftRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 100,
    kPutFieldNumber = 1,
    kGetFieldNumber = 2,
    kDeleteFieldNumber = 3,
  };
  // .foskvserverpb.RequestHeader header = 100;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::foskvserverpb::RequestHeader& header() const;
  PROTOBUF_NODISCARD ::foskvserverpb::RequestHeader* release_header();
  ::foskvserverpb::RequestHeader* mutable_header();
  void set_allocated_header(::foskvserverpb::RequestHeader* header);
  private:
  const ::foskvserverpb::RequestHeader& _internal_header() const;
  ::foskvserverpb::RequestHeader* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::foskvserverpb::RequestHeader* header);
  ::foskvserverpb::RequestHeader* unsafe_arena_release_header();

  // .foskvserverpb.PutRequest put = 1;
  bool has_put() const;
  private:
  bool _internal_has_put() const;
  public:
  void clear_put();
  const ::foskvserverpb::PutRequest& put() const;
  PROTOBUF_NODISCARD ::foskvserverpb::PutRequest* release_put();
  ::foskvserverpb::PutRequest* mutable_put();
  void set_allocated_put(::foskvserverpb::PutRequest* put);
  private:
  const ::foskvserverpb::PutRequest& _internal_put() const;
  ::foskvserverpb::PutRequest* _internal_mutable_put();
  public:
  void unsafe_arena_set_allocated_put(
      ::foskvserverpb::PutRequest* put);
  ::foskvserverpb::PutRequest* unsafe_arena_release_put();

  // .foskvserverpb.GetRequest get = 2;
  bool has_get() const;
  private:
  bool _internal_has_get() const;
  public:
  void clear_get();
  const ::foskvserverpb::GetRequest& get() const;
  PROTOBUF_NODISCARD ::foskvserverpb::GetRequest* release_get();
  ::foskvserverpb::GetRequest* mutable_get();
  void set_allocated_get(::foskvserverpb::GetRequest* get);
  private:
  const ::foskvserverpb::GetRequest& _internal_get() const;
  ::foskvserverpb::GetRequest* _internal_mutable_get();
  public:
  void unsafe_arena_set_allocated_get(
      ::foskvserverpb::GetRequest* get);
  ::foskvserverpb::GetRequest* unsafe_arena_release_get();

  // .foskvserverpb.DeleteRequest delete = 3;
  bool has_delete_() const;
  private:
  bool _internal_has_delete_() const;
  public:
  void clear_delete_();
  const ::foskvserverpb::DeleteRequest& delete_() const;
  PROTOBUF_NODISCARD ::foskvserverpb::DeleteRequest* release_delete_();
  ::foskvserverpb::DeleteRequest* mutable_delete_();
  void set_allocated_delete_(::foskvserverpb::DeleteRequest* delete_);
  private:
  const ::foskvserverpb::DeleteRequest& _internal_delete_() const;
  ::foskvserverpb::DeleteRequest* _internal_mutable_delete_();
  public:
  void unsafe_arena_set_allocated_delete_(
      ::foskvserverpb::DeleteRequest* delete_);
  ::foskvserverpb::DeleteRequest* unsafe_arena_release_delete_();

  void clear_type();
  TypeCase type_case() const;
  // @@protoc_insertion_point(class_scope:foskvserverpb.InternalRaftRequest)
 private:
  class _Internal;
  void set_has_put();
  void set_has_get();
  void set_has_delete_();

  inline bool has_type() const;
  inline void clear_has_type();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::foskvserverpb::RequestHeader* header_;
    union TypeUnion {
      constexpr TypeUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::foskvserverpb::PutRequest* put_;
      ::foskvserverpb::GetRequest* get_;
      ::foskvserverpb::DeleteRequest* delete__;
    } type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_foskv_2fapi_2ffoskvserverpb_2fraft_5finternal_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RequestHeader

// uint64 ID = 1;
inline void RequestHeader::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t RequestHeader::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t RequestHeader::id() const {
  // @@protoc_insertion_point(field_get:foskvserverpb.RequestHeader.ID)
  return _internal_id();
}
inline void RequestHeader::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void RequestHeader::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:foskvserverpb.RequestHeader.ID)
}

// -------------------------------------------------------------------

// InternalRaftRequest

// .foskvserverpb.RequestHeader header = 100;
inline bool InternalRaftRequest::_internal_has_header() const {
  return this != internal_default_instance() && _impl_.header_ != nullptr;
}
inline bool InternalRaftRequest::has_header() const {
  return _internal_has_header();
}
inline void InternalRaftRequest::clear_header() {
  if (GetArenaForAllocation() == nullptr && _impl_.header_ != nullptr) {
    delete _impl_.header_;
  }
  _impl_.header_ = nullptr;
}
inline const ::foskvserverpb::RequestHeader& InternalRaftRequest::_internal_header() const {
  const ::foskvserverpb::RequestHeader* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::foskvserverpb::RequestHeader&>(
      ::foskvserverpb::_RequestHeader_default_instance_);
}
inline const ::foskvserverpb::RequestHeader& InternalRaftRequest::header() const {
  // @@protoc_insertion_point(field_get:foskvserverpb.InternalRaftRequest.header)
  return _internal_header();
}
inline void InternalRaftRequest::unsafe_arena_set_allocated_header(
    ::foskvserverpb::RequestHeader* header) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:foskvserverpb.InternalRaftRequest.header)
}
inline ::foskvserverpb::RequestHeader* InternalRaftRequest::release_header() {
  
  ::foskvserverpb::RequestHeader* temp = _impl_.header_;
  _impl_.header_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::foskvserverpb::RequestHeader* InternalRaftRequest::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:foskvserverpb.InternalRaftRequest.header)
  
  ::foskvserverpb::RequestHeader* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::foskvserverpb::RequestHeader* InternalRaftRequest::_internal_mutable_header() {
  
  if (_impl_.header_ == nullptr) {
    auto* p = CreateMaybeMessage<::foskvserverpb::RequestHeader>(GetArenaForAllocation());
    _impl_.header_ = p;
  }
  return _impl_.header_;
}
inline ::foskvserverpb::RequestHeader* InternalRaftRequest::mutable_header() {
  ::foskvserverpb::RequestHeader* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:foskvserverpb.InternalRaftRequest.header)
  return _msg;
}
inline void InternalRaftRequest::set_allocated_header(::foskvserverpb::RequestHeader* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(header);
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.header_ = header;
  // @@protoc_insertion_point(field_set_allocated:foskvserverpb.InternalRaftRequest.header)
}

// .foskvserverpb.PutRequest put = 1;
inline bool InternalRaftRequest::_internal_has_put() const {
  return type_case() == kPut;
}
inline bool InternalRaftRequest::has_put() const {
  return _internal_has_put();
}
inline void InternalRaftRequest::set_has_put() {
  _impl_._oneof_case_[0] = kPut;
}
inline ::foskvserverpb::PutRequest* InternalRaftRequest::release_put() {
  // @@protoc_insertion_point(field_release:foskvserverpb.InternalRaftRequest.put)
  if (_internal_has_put()) {
    clear_has_type();
    ::foskvserverpb::PutRequest* temp = _impl_.type_.put_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.type_.put_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::foskvserverpb::PutRequest& InternalRaftRequest::_internal_put() const {
  return _internal_has_put()
      ? *_impl_.type_.put_
      : reinterpret_cast< ::foskvserverpb::PutRequest&>(::foskvserverpb::_PutRequest_default_instance_);
}
inline const ::foskvserverpb::PutRequest& InternalRaftRequest::put() const {
  // @@protoc_insertion_point(field_get:foskvserverpb.InternalRaftRequest.put)
  return _internal_put();
}
inline ::foskvserverpb::PutRequest* InternalRaftRequest::unsafe_arena_release_put() {
  // @@protoc_insertion_point(field_unsafe_arena_release:foskvserverpb.InternalRaftRequest.put)
  if (_internal_has_put()) {
    clear_has_type();
    ::foskvserverpb::PutRequest* temp = _impl_.type_.put_;
    _impl_.type_.put_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void InternalRaftRequest::unsafe_arena_set_allocated_put(::foskvserverpb::PutRequest* put) {
  clear_type();
  if (put) {
    set_has_put();
    _impl_.type_.put_ = put;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:foskvserverpb.InternalRaftRequest.put)
}
inline ::foskvserverpb::PutRequest* InternalRaftRequest::_internal_mutable_put() {
  if (!_internal_has_put()) {
    clear_type();
    set_has_put();
    _impl_.type_.put_ = CreateMaybeMessage< ::foskvserverpb::PutRequest >(GetArenaForAllocation());
  }
  return _impl_.type_.put_;
}
inline ::foskvserverpb::PutRequest* InternalRaftRequest::mutable_put() {
  ::foskvserverpb::PutRequest* _msg = _internal_mutable_put();
  // @@protoc_insertion_point(field_mutable:foskvserverpb.InternalRaftRequest.put)
  return _msg;
}

// .foskvserverpb.GetRequest get = 2;
inline bool InternalRaftRequest::_internal_has_get() const {
  return type_case() == kGet;
}
inline bool InternalRaftRequest::has_get() const {
  return _internal_has_get();
}
inline void InternalRaftRequest::set_has_get() {
  _impl_._oneof_case_[0] = kGet;
}
inline ::foskvserverpb::GetRequest* InternalRaftRequest::release_get() {
  // @@protoc_insertion_point(field_release:foskvserverpb.InternalRaftRequest.get)
  if (_internal_has_get()) {
    clear_has_type();
    ::foskvserverpb::GetRequest* temp = _impl_.type_.get_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.type_.get_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::foskvserverpb::GetRequest& InternalRaftRequest::_internal_get() const {
  return _internal_has_get()
      ? *_impl_.type_.get_
      : reinterpret_cast< ::foskvserverpb::GetRequest&>(::foskvserverpb::_GetRequest_default_instance_);
}
inline const ::foskvserverpb::GetRequest& InternalRaftRequest::get() const {
  // @@protoc_insertion_point(field_get:foskvserverpb.InternalRaftRequest.get)
  return _internal_get();
}
inline ::foskvserverpb::GetRequest* InternalRaftRequest::unsafe_arena_release_get() {
  // @@protoc_insertion_point(field_unsafe_arena_release:foskvserverpb.InternalRaftRequest.get)
  if (_internal_has_get()) {
    clear_has_type();
    ::foskvserverpb::GetRequest* temp = _impl_.type_.get_;
    _impl_.type_.get_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void InternalRaftRequest::unsafe_arena_set_allocated_get(::foskvserverpb::GetRequest* get) {
  clear_type();
  if (get) {
    set_has_get();
    _impl_.type_.get_ = get;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:foskvserverpb.InternalRaftRequest.get)
}
inline ::foskvserverpb::GetRequest* InternalRaftRequest::_internal_mutable_get() {
  if (!_internal_has_get()) {
    clear_type();
    set_has_get();
    _impl_.type_.get_ = CreateMaybeMessage< ::foskvserverpb::GetRequest >(GetArenaForAllocation());
  }
  return _impl_.type_.get_;
}
inline ::foskvserverpb::GetRequest* InternalRaftRequest::mutable_get() {
  ::foskvserverpb::GetRequest* _msg = _internal_mutable_get();
  // @@protoc_insertion_point(field_mutable:foskvserverpb.InternalRaftRequest.get)
  return _msg;
}

// .foskvserverpb.DeleteRequest delete = 3;
inline bool InternalRaftRequest::_internal_has_delete_() const {
  return type_case() == kDelete;
}
inline bool InternalRaftRequest::has_delete_() const {
  return _internal_has_delete_();
}
inline void InternalRaftRequest::set_has_delete_() {
  _impl_._oneof_case_[0] = kDelete;
}
inline ::foskvserverpb::DeleteRequest* InternalRaftRequest::release_delete_() {
  // @@protoc_insertion_point(field_release:foskvserverpb.InternalRaftRequest.delete)
  if (_internal_has_delete_()) {
    clear_has_type();
    ::foskvserverpb::DeleteRequest* temp = _impl_.type_.delete__;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.type_.delete__ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::foskvserverpb::DeleteRequest& InternalRaftRequest::_internal_delete_() const {
  return _internal_has_delete_()
      ? *_impl_.type_.delete__
      : reinterpret_cast< ::foskvserverpb::DeleteRequest&>(::foskvserverpb::_DeleteRequest_default_instance_);
}
inline const ::foskvserverpb::DeleteRequest& InternalRaftRequest::delete_() const {
  // @@protoc_insertion_point(field_get:foskvserverpb.InternalRaftRequest.delete)
  return _internal_delete_();
}
inline ::foskvserverpb::DeleteRequest* InternalRaftRequest::unsafe_arena_release_delete_() {
  // @@protoc_insertion_point(field_unsafe_arena_release:foskvserverpb.InternalRaftRequest.delete)
  if (_internal_has_delete_()) {
    clear_has_type();
    ::foskvserverpb::DeleteRequest* temp = _impl_.type_.delete__;
    _impl_.type_.delete__ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void InternalRaftRequest::unsafe_arena_set_allocated_delete_(::foskvserverpb::DeleteRequest* delete_) {
  clear_type();
  if (delete_) {
    set_has_delete_();
    _impl_.type_.delete__ = delete_;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:foskvserverpb.InternalRaftRequest.delete)
}
inline ::foskvserverpb::DeleteRequest* InternalRaftRequest::_internal_mutable_delete_() {
  if (!_internal_has_delete_()) {
    clear_type();
    set_has_delete_();
    _impl_.type_.delete__ = CreateMaybeMessage< ::foskvserverpb::DeleteRequest >(GetArenaForAllocation());
  }
  return _impl_.type_.delete__;
}
inline ::foskvserverpb::DeleteRequest* InternalRaftRequest::mutable_delete_() {
  ::foskvserverpb::DeleteRequest* _msg = _internal_mutable_delete_();
  // @@protoc_insertion_point(field_mutable:foskvserverpb.InternalRaftRequest.delete)
  return _msg;
}

inline bool InternalRaftRequest::has_type() const {
  return type_case() != TYPE_NOT_SET;
}
inline void InternalRaftRequest::clear_has_type() {
  _impl_._oneof_case_[0] = TYPE_NOT_SET;
}
inline InternalRaftRequest::TypeCase InternalRaftRequest::type_case() const {
  return InternalRaftRequest::TypeCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace foskvserverpb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_foskv_2fapi_2ffoskvserverpb_2fraft_5finternal_2eproto
